### ISSUE TITLE
Makefile

### ISSUE THREAD

**Issue by inesKKK** [valfur03/Mille-Bornes#9]
Please add a makefile!

**Comment by valfur03** [comment]
I am on it ;)

**Comment by valfur03** [comment]
The makefile is added! Tell me if there is something wrong, I’ve never done something like this before

**Comment by inesKKK** [comment]
It seems ok for me. Thanks (good for your record, I hope we will see you next year).

**Comment by valfur03** [comment]
Thank you! Can you tell me which school/university do you represent?

**Comment by inesKKK** [comment]
I am not sure I am allowed to it, sorry.

**Comment by valfur03** [comment]
Never mind. I hope I’ll see you soon too then!
